title: Karim Abdelali
description: Personal website
baseurl: ''
url: ''

permalink: pretty

collections:
  notes:
    output: true
    permalink: /:slug/

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: notes
    values:
      layout: post
